{% set name = "colcon-metadata" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b472a9f4c93598379ad32f9b95a184f4d1b649c5cc52ca084bab9400c7b0c03e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - colcon-core
    - PyYAML

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to fetch and manage package metadata from repositories.

extra:
  recipe-maintainers:
    - j-rivero
    - seanyen
    - wolfv
