{% set name = "colcon-metadata" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 799193bf41a2c294a52f58b0c7c036d6c0524c0ef63ced6d3f210edd78fae63f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - colcon-core
    - PyYAML

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to fetch and manage package metadata from repositories.

extra:
  recipe-maintainers:
    - j-rivero
    - seanyen
    - wolfv
